import { type Session } from "next-auth";
import type { AppProps } from "next/app";
import { ClerkProvider } from '@clerk/nextjs'
import { type AppType } from "next/app";
import { api } from "npm/utils/api";
import Head from "next/head";
import "npm/styles/globals.css";

//used to implement react notifications https://react-hot-toast.com
import { Toaster } from "react-hot-toast";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { ...pageProps },
}: AppProps) => {
  return (
    <ClerkProvider {...pageProps}>
      <Head>
        <title>Emojiitch</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster position="bottom-center"/>
      <Component {...pageProps} />
    </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
